ALTER TABLE sites ADD COLUMN IF NOT EXISTS rariran_content_id TEXT DEFAULT NULL;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS rariran_content_slug TEXT DEFAULT NULL;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS rariran_content_status TEXT DEFAULT NULL;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS checked_source_url_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;

ALTER TABLE elements ADD COLUMN IF NOT EXISTS rariran_content_deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
