ALTER TABLE collections ADD COLUMN IF NOT EXISTS x6_post_id TEXT DEFAULT NULL;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS x6_post_slug TEXT DEFAULT NULL;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS x6_post_status TEXT DEFAULT NULL;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS x6_post_deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS checked_source_url_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
